# Generated by Django 5.0.7 on 2024-07-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_user_address_user_age_user_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
