# Generated by Django 5.0.7 on 2024-07-31 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('user',)},
        ),
    ]
