# Generated by Django 5.0.7 on 2025-09-29 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_user_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Source Categories',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='source_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.sourcecategory'),
        ),
        migrations.CreateModel(
            name='ValueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Value Categories',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='value_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.valuecategory'),
        ),
    ]
