# Generated by Django 5.0.7 on 2025-09-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_sourcecategory_lead_source_category_valuecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
