# Generated by Django 5.0.7 on 2025-09-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Erkek'), ('F', 'Kadın'), ('O', 'Diğer')], max_length=1, null=True),
        ),
    ]
