# Generated by Django 5.0.7 on 2025-10-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_alter_lead_email_alter_lead_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_images/'),
        ),
    ]
