# Generated by Django 5.0.7 on 2026-02-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='profile_image',
            field=models.FileField(blank=True, help_text='Lead profile photo', null=True, upload_to='lead_photos/'),
        ),
    ]
