"""
Django settings for djcrm project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (always from project root; override existing env)
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if h.strip()
]

# Render.com: automatically allow the .onrender.com domain
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# CSRF trusted origins (required for Django 4+ in production)
# Without this, all form submissions return 403 Forbidden on Render!
CSRF_TRUSTED_ORIGINS = [
    h.strip()
    for h in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if h.strip()
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
 
    # Third party apps
    'crispy_forms',
    "crispy_tailwind",
    'phonenumber_field',
    'gmailapi_backend',

    # Local apps
    'leads',
    'agents',
    'organisors',
    'ProductsAndStock',
    'orders',
    'finance',
    'tasks',
    'activity_log',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djcrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tasks.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'djcrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Set DB_ENGINE to django.db.backends.postgresql (and DB_* vars) to use PostgreSQL.
# Leave unset for SQLite (development default).

# Database configuration
# Priority: DATABASE_URL > DB_ENGINE/DB_* env vars > SQLite (default)
_database_url = os.getenv('DATABASE_URL')
_db_engine = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')

if _database_url:
    # Neon pooled connection: add search_path to URL (fixes "no schema selected" with PgBouncer)
    if 'options=' not in _database_url.lower():
        _sep = '&' if '?' in _database_url else '?'
        _database_url = f"{_database_url}{_sep}options=-c%20search_path%3Dpublic"
    # DATABASE_URL: Render, Neon, or other PaaS providers
    _db_config = dj_database_url.config(
        default=_database_url,
        conn_max_age=600,
        conn_health_checks=True,
    )
    # Neon serverless compatibility
    _db_config['DISABLE_SERVER_SIDE_CURSORS'] = True
    if 'OPTIONS' not in _db_config:
        _db_config['OPTIONS'] = {}
    _db_config['OPTIONS'].setdefault('sslmode', 'require')
    DATABASES = {'default': _db_config}
elif _db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    _db_options = {}
    if os.getenv('DB_SSL', '').lower() in ('1', 'true', 'yes'):
        _db_options['sslmode'] = 'require'
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.getenv('DB_NAME', 'djcrm'),
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': _db_options if _db_options else {},
        }
    }

# Test sırasında SQLite kullan (PostgreSQL kullanıcısında CREATEDB yoksa)
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',  # Bellekte geçici DB
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
TIME_ZONE = 'Europe/Istanbul'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
STATIC_ROOT = BASE_DIR / 'static_root'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'leads.User'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'leads.authentication.EmailOrUsernameModelBackend',
]

# Email: Gmail API (Render blocks SMTP ports) or SMTP for local dev
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'your-email@gmail.com')
_use_gmail_api = os.getenv('USE_GMAIL_API', '').lower() in ('true', '1', 'yes')
# Auto-enable Gmail API on Render (RENDER_EXTERNAL_HOSTNAME is set by Render)
if _use_gmail_api or os.getenv('RENDER_EXTERNAL_HOSTNAME'):
    EMAIL_BACKEND = 'gmailapi_backend.mail.GmailBackend'
    GMAIL_API_CLIENT_ID = os.getenv('GMAIL_API_CLIENT_ID')
    GMAIL_API_CLIENT_SECRET = os.getenv('GMAIL_API_CLIENT_SECRET')
    GMAIL_API_REFRESH_TOKEN = os.getenv('GMAIL_API_REFRESH_TOKEN')
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'your-email@gmail.com')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'your-app-password-here')
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login'
LOGOUT_REDIRECT_URL = '/'

# Site URL for email links (used in management commands where request object is unavailable)
# In views, use request.build_absolute_uri() instead.
_render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')
SITE_URL = os.getenv(
    'SITE_URL',
    f'https://{_render_host}' if _render_host else 'http://127.0.0.1:8000'
)
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = 'tailwind'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Database connection age (seconds) - keeps connections open for reuse
CONN_MAX_AGE = 600 if not DEBUG else 0

# Security settings for production
if not DEBUG:
    # Render.com uses a reverse proxy – tell Django the original request was HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True

    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
