# Generated by Django 5.0.7 on 2025-09-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAndStock', '0002_productsandstock_organisation'),
        ('leads', '0022_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsandstock',
            unique_together={('product_name', 'organisation')},
        ),
    ]
