# Generated by Django 5.0.7 on 2025-09-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAndStock', '0003_alter_productsandstock_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsandstock',
            name='minimum_stock_level',
            field=models.IntegerField(default=0, help_text='Minimum stock level for alerts'),
        ),
    ]
