# Generated by Django 5.0.7 on 2025-10-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAndStock', '0006_category_productsandstock_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsandstock',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProductsAndStock.category'),
        ),
        migrations.AlterField(
            model_name='productsandstock',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProductsAndStock.subcategory'),
        ),
    ]
