# Generated by Django 5.0.7 on 2025-10-01 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAndStock', '0007_make_category_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productsandstock',
            name='cost_price',
            field=models.FloatField(default=0.0, help_text='Purchase/production cost', verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='productsandstock',
            name='discount_amount',
            field=models.FloatField(default=0.0, help_text='Fixed discount amount'),
        ),
        migrations.AddField(
            model_name='productsandstock',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsandstock',
            name='discount_percentage',
            field=models.FloatField(default=0.0, help_text='Discount percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='productsandstock',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsandstock',
            name='product_price',
            field=models.FloatField(verbose_name='Selling Price'),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('price_change', models.FloatField()),
                ('change_type', models.CharField(choices=[('INCREASE', 'Price Increase'), ('DECREASE', 'Price Decrease'), ('DISCOUNT', 'Discount Applied'), ('BULK_UPDATE', 'Bulk Price Update'), ('MANUAL', 'Manual Update')], max_length=20)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_percentage', models.FloatField(blank=True, help_text='Discount percentage if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='ProductsAndStock.productsandstock')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
