# Generated by Django 5.0.7 on 2025-10-01 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAndStock', '0008_productsandstock_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('OUT_OF_STOCK', 'Out of Stock Alert'), ('OVERSTOCK', 'Overstock Alert'), ('NO_SALES', 'No Sales Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='ProductsAndStock.productsandstock')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('RESTOCK', 'Restock Recommendation'), ('REDUCE_STOCK', 'Reduce Stock Recommendation'), ('DISCOUNT', 'Discount Recommendation'), ('DISCONTINUE', 'Discontinue Recommendation')], max_length=20)),
                ('suggested_quantity', models.IntegerField(blank=True, help_text='Suggested stock quantity', null=True)),
                ('suggested_discount', models.FloatField(blank=True, help_text='Suggested discount percentage', null=True)),
                ('reason', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score (0-100)')),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_recommendations', to='ProductsAndStock.productsandstock')),
            ],
            options={
                'verbose_name': 'Stock Recommendation',
                'verbose_name_plural': 'Stock Recommendations',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_sales', models.IntegerField(default=0, help_text='Total quantity sold today')),
                ('total_revenue', models.FloatField(default=0.0, help_text='Total revenue from sales today')),
                ('avg_daily_sales', models.FloatField(default=0.0, help_text='Average daily sales (last 30 days)')),
                ('last_sale_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_stats', to='ProductsAndStock.productsandstock')),
            ],
            options={
                'verbose_name': 'Sales Statistics',
                'verbose_name_plural': 'Sales Statistics',
                'ordering': ['-total_sales'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
