# Generated by Django 5.0.7 on 2026-02-09 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0025_add_lead_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('organisor_created', 'Organisor oluşturuldu'), ('organisor_updated', 'Organisor güncellendi'), ('organisor_deleted', 'Organisor silindi'), ('agent_created', 'Agent oluşturuldu'), ('agent_updated', 'Agent güncellendi'), ('agent_deleted', 'Agent silindi'), ('product_created', 'Ürün oluşturuldu'), ('product_updated', 'Ürün güncellendi'), ('product_deleted', 'Ürün silindi'), ('price_increased', 'Fiyat artırıldı'), ('price_decreased', 'Fiyat düşürüldü'), ('price_bulk_update', 'Toplu fiyat güncellemesi'), ('order_created', 'Sipariş oluşturuldu'), ('order_updated', 'Sipariş güncellendi'), ('order_cancelled', 'Sipariş iptal edildi'), ('lead_created', 'Lead oluşturuldu'), ('lead_updated', 'Lead güncellendi'), ('lead_deleted', 'Lead silindi')], max_length=32, verbose_name='İşlem')),
                ('object_type', models.CharField(blank=True, choices=[('organisor', 'Organisor'), ('agent', 'Agent'), ('product', 'Ürün / Stok'), ('order', 'Sipariş'), ('lead', 'Lead')], max_length=20, null=True, verbose_name='Nesne tipi')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nesne ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Nesne özeti')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Örn: eski_fiyat, yeni_fiyat, ürün_adı', verbose_name='Ek detaylar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='leads.userprofile', verbose_name='Organizasyon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Aktivite kaydı',
                'verbose_name_plural': 'Aktivite kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
