# Generated by Django 5.0.7 on 2026-02-09 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
        ('leads', '0025_add_lead_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity log entry', 'verbose_name_plural': 'Activity logs'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='affected_agent',
            field=models.ForeignKey(blank=True, help_text='Agent who is affected by this action (e.g. lead/task assigned to them, order for their lead)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs_affecting', to='leads.agent', verbose_name='Affected agent'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('organisor_created', 'Organisor created'), ('organisor_updated', 'Organisor updated'), ('organisor_deleted', 'Organisor deleted'), ('agent_created', 'Agent created'), ('agent_updated', 'Agent updated'), ('agent_deleted', 'Agent deleted'), ('product_created', 'Product created'), ('product_updated', 'Product updated'), ('product_deleted', 'Product deleted'), ('price_increased', 'Price increased'), ('price_decreased', 'Price decreased'), ('price_bulk_update', 'Bulk price update'), ('order_created', 'Order created'), ('order_updated', 'Order updated'), ('order_cancelled', 'Order cancelled'), ('lead_created', 'Lead created'), ('lead_updated', 'Lead updated'), ('lead_deleted', 'Lead deleted'), ('task_created', 'Task created'), ('task_updated', 'Task updated'), ('task_deleted', 'Task deleted')], max_length=32, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='E.g. old_price, new_price, product_name', verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Object summary'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_type',
            field=models.CharField(blank=True, choices=[('organisor', 'Organisor'), ('agent', 'Agent'), ('product', 'Product / Stock'), ('order', 'Order'), ('lead', 'Lead'), ('task', 'Task')], max_length=20, null=True, verbose_name='Object type'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
