# Generated by Django 5.0.7 on 2024-07-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='OrderDay',
            new_name='order_day',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='order_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
