# Generated by Django 5.0.7 on 2024-07-25 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_date_added_lead_description_lead_email_and_more'),
        ('orders', '0002_rename_orderday_orders_order_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
    ]
