# Generated by Django 5.0.7 on 2024-07-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAndStock', '0002_productsandstock_organisation'),
        ('orders', '0003_orders_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductsAndStock.productsandstock'),
        ),
    ]
