# Generated by Django 5.0.7 on 2024-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
