# Generated by Django 5.0.7 on 2024-07-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_amount',
        ),
    ]
