# Generated by Django 5.0.7 on 2024-07-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orders_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
