# Generated by Django 5.0.7 on 2024-08-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orders_product_remove_orders_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
