# Generated by Django 5.0.7 on 2024-08-02 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderproduct_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 2, 9, 5, 47, 64014)),
            preserve_default=False,
        ),
    ]
