# Generated by Django 5.0.7 on 2024-08-02 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orders_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
